name: Build Docker Container Image
on:
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-22.04
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          registry: ghcr.io
          tags: ghcr.io/iac-reshaping/compiler-testing/builder:v1.0.0,ghcr.io/iac-reshaping/compiler-testing/builder:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
